# Site Settings
baseurl: ""
url : "https://E-RROR.github.io"

# Blog Settings
theme_settings :
  title : Sina Farhadi | سینا فرهادی
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/avatar.jpeg
    username : سینا فرهادی
    description : گیک برنامه نویسی و هوش مصنوعی
    experience :
    skills :
        
  # Icons
  icons :
    email:
    linkedin: https://www.linkedin.com/in/sina-farhadi-profile/
    github: E-RROR
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:
    stackoverflow: 12712466/sina

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
